trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: dev
  - name: DOCKER-REPOSITORY
    value: $(AWS-ACCOUNT-ID).dkr.ecr.$(AWS-REGION).amazonaws.com/$(DOCKER-REPOSITORY-NAME)

steps:
- script: |
    aws ecr get-login-password --region $(AWS-REGION) | docker login --username AWS --password-stdin $(AWS-ACCOUNT-ID).dkr.ecr.$(AWS-REGION).amazonaws.com
  displayName: 'Login to AWS'
  env:
    AWS_ACCESS_KEY_ID: $(AWS-ACCESS-KEY-ID)
    AWS_SECRET_ACCESS_KEY: $(AWS-SECRET-ACCESS-KEY)

- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: $(DOCKER-REPOSITORY)
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: |
      latest

