version: '2.1'
services:
  ParentContactWeb:
    build:
      context: ./ParentContactWeb
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
  reverseproxy:
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    links :
      - ParentContactWeb